# pre-commit install
# pre-commit run --all-files
# git commit . -m 'quick fix' --no-verify
#files: |
#  (?x)^(
#       endpoints.py|
#       score_api.py|
#  )$
repos:
  - repo: meta
    hooks:
      - id: identity
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: requirements-txt-fixer
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
#  - repo: https://github.com/econchick/interrogate
#    rev: 1.5.0  # or master if you're bold
#    hooks:
#      - id: interrogate
#        args: [ --verbose , --fail-under=100 ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
        - id: isort
          name: isort
          language: system
          types: [ python ]
          fail_fast: true
          args: [".", "--profile", "black", "--filter-files"]
          pass_filenames: false
          verbose: true
  # - repo: local
  #   hooks:
  #     - id: unittest
  #       name: unittest
  #       entry: ../venv/bin/python3 -m unittest
  #       language: system
  #       fail_fast: true
  #       args: ["discover", "-v" ]
  #       pass_filenames: false
  #       verbose: true
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # pick a git hash / tag to point to
    hooks:
        - id: flake8
          args:
            [
              "--max-line-length=121",
              "--ignore=E402,W503,E101,W191,E501",
            ]
  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.4
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [ python ]
        verbose: true
        args:
          [
            "--variable-rgx='[a-z0-9_]{1,30}$'",
            "--reports=n",
            "--fail-under=8",
            "--max-line-length=121",
            "--ignore=__init__.py",
#            "--ignored-classes=SQLObject,scoped_session,SQLAlchemy",
#            "--disable=W0311,C0103,C0111,R0801, C0301,C0209",
             "--disable=C0103",
            "--score=yes"
          ]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: bandit
        verbose: true
        args:
          [
            "--skip=B303,B105,B608,B201",
            "--verbose"
          ]
#  - repo: local
#    hooks:
#      - id: pycodestyle
#        name: pycodestyle
#        entry: ../venv/bin/python -m pycodestyle
#        language: system
#        types: [ python ]
#        verbose: true
#        files: |
#          (?x)^(
#               s3_tools.py|
#               ssm_tools.py
#          )$
#        args:
#          [
#            "--count",
#            "--max-line-length=121",
#            "--ignore=E501,W503,E402,E203"
#          ]
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      name: Black
      language: system
      types: [ python ]
      fail_fast: false
      verbose: true
      args: [ "--line-length=121", "." ]
